### ISSUE TITLE
Javascript error in chrome console

### ISSUE THREAD

**Issue by azimpradhan** [ProjectCodaW/CoDaw#19]
Uncaught TypeError: Cannot read property 'wavesurfer' of null

This error occurs in 08152e82675f1eb5137e679081e642020039f039
'Add sound object per track'. The error occurs before the WAAX submodule merge.

<img width="1268" alt="screen shot 2016-01-22 at 6 22 56 pm" src="https://cloud.githubusercontent.com/assets/1752973/12527697/5c79462e-c135-11e5-9e81-53d7227dbdcb.png">

**Comment by azimpradhan** [comment]
@mattahorton, could you take look at this, when you get a chance?

**Comment by felakuti4life** [comment]
fixed by f4ce920f4e7d8f595d392fe41257995408525e3e
