### ISSUE TITLE
Hard-coded absolute url for telephone.wav fails to load resource in production

### ISSUE THREAD

**Issue by azimpradhan** [ProjectCodaW/CoDaw#22]
https://github.com/ProjectCodaW/CoDaw/commit/08152e82675f1eb5137e679081e642020039f039#diff-993c0e4e0bbd9e4d970944da5e440408R23

the latest deploy can be viewed at:
dev.codaw.co
Open the chrome console to see the error.

**Comment by felakuti4life** [comment]
Is this a duplicate of #21 ?

**Comment by azimpradhan** [comment]
no, it is a related but separate issue. It has to do with hardcoding 'localhost:3000'. You can see the code that it deals with using the link above.

**Comment by mattahorton** [comment]
This was fixed via #27

**Comment by azimpradhan** [comment]
#27 was reverted, because changes did not work in production. We will have to look into it in order to merge. #30 fixes this issue.
